Repository typelevel/grackle, pull requests merged in 2023-11, with the labels that each got.

#258 Parse type/schema extensions
  build.sbt
  modules/core/src/main/scala/ast.scala
  modules/core/src/main/scala/parser.scala
  modules/core/src/main/scala/schema.scala
  modules/core/src/test/scala/extensions/ExtensionsSuite.scala
  modules/core/src/test/scala/parser/ParserSuite.scala
  modules/core/src/test/scala/schema/SchemaSuite.scala
  modules/core/src/test/scala/sdl/SDLSuite.scala
Labels: enhancement

#505 Rely on sbt-typelevel defaults for organization
  benchmarks/src/main/scala/ParserBenchmark.scala
  build.sbt
Labels: housekeeping

#516 Generated README.md using mdoc
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  build.sbt
  docs/CONTRIBUTING.md
  docs/index.md
  header.md
  modules/docs/src/main/scala/grackle/Output.scala
Labels: documentation

#519 Fixes for empty SQL sub-objects
  build.sbt
  modules/sql/shared/src/main/scala/SqlMapping.scala
  modules/sql/shared/src/test/scala/SqlMixedMapping.scala
  modules/sql/shared/src/test/scala/SqlMixedSuite.scala
Labels: bug

#521 Elaborate introspection in out of line fragments
  modules/core/src/main/scala/compiler.scala
  modules/core/src/test/scala/introspection/IntrospectionSuite.scala
  modules/generic/src/main/scala-2/genericmapping2.scala
Labels: bug
